import React, { createContext, useContext, useState, ReactNode } from 'react';

type Locale = 'en' | 'ms';

const translations = {
  en: {
    appTitle: 'SmartInvoice',
    newInvoice: 'New Invoice',
    printPdf: 'Print / PDF',
    preview: 'Preview',
    editor: 'Editor',
    save: 'Save',
    aiTitle: 'AI Assistant',
    aiDesc: 'Describe your work (e.g., "Web design for 20 hours at RM150/hr for Maju Jaya") and let AI fill the invoice.',
    aiPlaceholder: 'Paste email snippet or type rough notes...',
    aiDisclaimer: 'Data sent to AI for processing.',
    invoiceDetails: 'Invoice Details',
    number: 'Invoice No.',
    currency: 'Currency',
    date: 'Date',
    dueDate: 'Due Date',
    fromTo: 'From & To',
    fromSender: 'Supplier / Freelancer Details',
    toClient: 'Bill To',
    businessName: 'Name / Business Name',
    regNo: 'Reg. / IC No.',
    sstNo: 'SST ID (Optional)',
    email: 'Email',
    address: 'Address',
    clientName: 'Client Name',
    clientEmail: 'Client Email',
    clientAddress: 'Client Address',
    lineItems: 'Line Items',
    description: 'Description',
    qty: 'Qty',
    rate: 'Unit Price',
    amount: 'Amount',
    addItem: 'Add Item',
    settingsNotes: 'Settings & Notes',
    taxSst: 'Tax / SST (%)',
    termsNotes: 'Terms & Notes',
    taxInvoice: 'TAX INVOICE',
    simpleInvoice: 'INVOICE',
    billTo: 'Bill To',
    subtotal: 'Subtotal',
    total: 'Total',
    generatedBy: 'Generated by SmartInvoice AI',
    noItems: 'No items added yet.',
    generating: 'Generating Invoice...',
    confirmNew: 'Create a new invoice? This will clear current client details and increment the invoice number.',
    computerGenerated: 'This is a computer-generated document. No signature is required.',
    apiKeyError: 'System Error: API Key is missing or invalid. Please check configuration.',
    aiError: 'Could not interpret text. Please try again with clearer details.',
    history: 'History',
    noHistory: 'No saved invoices.',
    branding: 'Branding',
    logo: 'Company Logo',
    logoDesc: 'Upload a square or rectangular image (PNG/JPG).',
    signature: 'Digital Signature',
    clear: 'Clear',
    authorizedSignature: 'Authorized Signature'
  },
  ms: {
    appTitle: 'SmartInvoice',
    newInvoice: 'Invois Baru',
    printPdf: 'Cetak / PDF',
    preview: 'Pratonton',
    editor: 'Editor',
    save: 'Simpan',
    aiTitle: 'Pembantu AI',
    aiDesc: 'Terangkan kerja anda (cth: "Reka bentuk web 20 jam, RM150/jam untuk Maju Jaya") dan biarkan AI mengisi invois.',
    aiPlaceholder: 'Tampal petikan emel atau taip nota...',
    aiDisclaimer: 'Data dihantar ke AI untuk diproses.',
    invoiceDetails: 'Butiran Invois',
    number: 'No. Invois',
    currency: 'Mata Wang',
    date: 'Tarikh',
    dueDate: 'Tarikh Akhir',
    fromTo: 'Daripada & Kepada',
    fromSender: 'Butiran Pembekal / Freelancer',
    toClient: 'Kepada',
    businessName: 'Nama / Nama Perniagaan',
    regNo: 'No. Pend. / KP',
    sstNo: 'No. SST (Pilihan)',
    email: 'Emel',
    address: 'Alamat',
    clientName: 'Nama Pelanggan',
    clientEmail: 'Emel Pelanggan',
    clientAddress: 'Alamat Pelanggan',
    lineItems: 'Item',
    description: 'Keterangan',
    qty: 'Kuantiti',
    rate: 'Harga Unit',
    amount: 'Jumlah',
    addItem: 'Tambah Item',
    settingsNotes: 'Tetapan & Nota',
    taxSst: 'Cukai / SST (%)',
    termsNotes: 'Terma & Nota',
    taxInvoice: 'INVOIS CUKAI',
    simpleInvoice: 'INVOIS',
    billTo: 'Kepada',
    subtotal: 'Jumlah Kecil',
    total: 'Jumlah Besar',
    generatedBy: 'Dijana oleh SmartInvoice AI',
    noItems: 'Tiada item ditambah.',
    generating: 'Menjana Invois...',
    confirmNew: 'Buat invois baru? Ini akan memadam butiran pelanggan semasa dan menambah nombor invois.',
    computerGenerated: 'Ini adalah dokumen cetakan komputer. Tandatangan tidak diperlukan.',
    apiKeyError: 'Ralat Sistem: Kunci API hilang atau tidak sah. Sila semak konfigurasi.',
    aiError: 'Tidak dapat mentafsir teks. Sila cuba lagi dengan butiran yang lebih jelas.',
    history: 'Sejarah',
    noHistory: 'Tiada invois disimpan.',
    branding: 'Penjenamaan',
    logo: 'Logo Syarikat',
    logoDesc: 'Muat naik imej (PNG/JPG).',
    signature: 'Tandatangan Digital',
    clear: 'Padam',
    authorizedSignature: 'Tandatangan Sah'
  }
};

interface I18nContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: keyof typeof translations['en']) => string;
}

const I18nContext = createContext<I18nContextType | undefined>(undefined);

export const I18nProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [locale, setLocale] = useState<Locale>('en');

  const t = (key: keyof typeof translations['en']) => {
    return translations[locale][key] || key;
  };

  return (
    <I18nContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </I18nContext.Provider>
  );
};

export const useI18n = () => {
  const context = useContext(I18nContext);
  if (!context) {
    throw new Error('useI18n must be used within an I18nProvider');
  }
  return context;
};